### ISSUE TITLE
threadlocal result is not inferrable

### ISSUE THREAD

**Issue by Kolaru** [JuliaSIMD/Polyester.jl#112]
The `threadlocal` which appears outside the `@batch` is not inferrable, even if the type is given in the macro.

The following code (inspired from the README)
```julia
function f()
    @batch threadlocal=rand(10:99)::Int for i in 0:9
        threadlocal += 1
    end
    sum(threadlocal)
end

@code_warntype f()
```
tells me that the content of `threadlocal` and the return type of the function have both type `Any`.

**Comment by chriselrod** [comment]
This can be done in an inferrable and, if the type `isbits` (such as `Int`), also a 0-allocation manner.

If anyone feels like doing this, I'd be happy to answer questions/help out.
Basic idea:
```julia
using StrideArraysCore, CPUSummary, Static
T = # type annotation
if isbitstype(T)
  CLS = CPUSummary.cache_linesize()
  ts = static(sizeof(T))
  ncols = CPUSummary.sys_threads()
  nrows = cld(CLS, ts)
  threadlocal_matrix = StrideArray{T](undef, (nrows, ncols))
  threadlocal = threadlocal_matrix[1, :] # slice is a view
```
`threadlocal_matrix` should be allocated on the stack.
Some care will have to be taken that it doesn't escape, but `Polyester` itself will `GC.@preserve` arrays and use `PtrArray` views of them.

Of course, the `sum` from that example will not do this, forcing an allocation.

**Comment by chriselrod** [comment]
> Of course, the sum from that example will not do this, forcing an allocation.

So my suggestion there is to extract it to a tuple.

**Comment by GianlucaFuwa** [comment]
I'm also a user of this feature and have stumbled upon this problem. Am I wrong in believing that the type-instability stems from accessing `threadlocal` outside of  `enclose(...)`'s scope, since it then is a `Vector{T}` instead of a `T` as asserted in `threadlocal=init()::T`?

If I add the line: 
```julia
var"##THREADLOCAL#OUT##" = $(threadlocal === Symbol("")) ? nothing : $(esc(threadlocal_var))
```
at the end of the final `quote` of `enclose()`, the instability (checked with both `@code_warntype` and `@descend`) vanishes and the performance in the previous example improves:
```julia
using Polyester

function f_old()
    @batch threadlocal=rand(10:99)::Int for i in 0:9
        threadlocal += 1
    end
    sum(threadlocal)
end

function f_new()
    out = @batch threadlocal=rand(10:99)::Int for i in 0:9
        threadlocal += 1
    end
    sum(out)
end
```
```julia
@btime f_old()
64.562 ns (2 allocations: 144 bytes)

@btime f_new()
113.218 ns (3 allocations: 160 bytes)
```
Not sure if this is a good way to go about it.

I would love to implement @chriselrod 's idea using `StrideArray`s  to make this allocation-less, though I am afraid that my knowledge on closures might not be sufficient.
