### ISSUE TITLE
Documentation Question

### ISSUE THREAD

**Issue by tknopp** [JuliaSIMD/Polyester.jl#56]
Hi @chriselrod,

these are rather questions but probably also also something that could belong into the documentation, thus I thought to open an issue.

After reading the documentation it it still not clear to me
- What threading utility is Polyester using? Is it just OS threads with a threadpool?
- If yes, where does that differ from `@threads`? So why does `@threads` have an overhead at all? I thought a thread pool takes away most of the overhead (thread creation).
- Do I need to start Julia with `-t` to profit from polyester? (apparently yes, which might answer my question 1)
- Is nesting possible?
- How does it interplay with Julia threads, i.e. if I have background thread running can I then still use Polyester?

Thanks,

Tobi

**Comment by chriselrod** [comment]
> What threading utility is Polyester using? Is it just OS threads with a threadpool?

Given you also filed an issue at [ThreadingUtilities.jl](https://github.com/JuliaSIMD/ThreadingUtilities.jl/), I suppose you've seen it.
On `__init__()`, ThreadingUtilities starts `min(Sys.CPU_THREADS,Threads.nthreads())-1` tasks.
These tasks then go to sleep.

When you try and `ThreadingUtilities.launch` work on one of these threads, which is what Polyester.jl, LoopVectorization.jl, and Octavian.jl do, they'll change the status of a pointer to indicate they have work to do.
Then they'll check if the task is asleep (`state == WAIT`). If it is asleep, they'll wake the task.

Once a task finishes the work they do, they'll spin for a bit (quickly checking for new work to do), and then go to sleep if they haven't been given anything to do.

2) If yes, where does that differ from `@threads`?

`@threads` creates new tasks instead of reusing old (which takes about 60ns on average, allocating 448 bytes), plus Julia's scheduler is very slow, so it takes a long time for these to get started, instead of starting immediately as with `ThreadingUtilities` when a thread is already awake.

> Do I need to start Julia with -t to profit from polyester? (apparently yes, which might answer my question 1)

Yes.

> Is nesting possible?

Anything based on `PolyesterWeave.jl` (which includes LoopVectorization, Octavian, and of course Polyester) are safe to nest. Threading will essentially be disabled for all of the inner threaded programs, unless there were threads remaining from the outer threaded program.

> How does it interplay with Julia threads, i.e. if I have background thread running can I then still use Polyester?

Not well. It's likely to cause problems.

**Comment by tknopp** [comment]
Thank you for the very helpful answer! Task creation is thus the issue of `@threads`. I will still stick with Polyester.jl in my package NFFT.jl since in that use case overhead will likely be an issue.
